### ISSUE TITLE
Error when you use actions

### ISSUE THREAD

**Issue by richardvaldivieso** [yarbsemaj/sveltekit-serverless-starter#1]
I was reviewing your example, but I noticed that when I execute a POST, I got the following response

<img width="493" alt="image" src="https://github.com/yarbsemaj/sveltekit-serverless-starter/assets/6244759/1c491f50-792f-4f18-9898-44929bde2705">

This occurred in the following endpont
https://dm62vbwrqj27t.cloudfront.net/sverdle?/enter

It seems that CloudFront does not like that format for the query string. Have you tried to fix this?

**Comment by yarbsemaj** [comment]
Hi @richardvaldivieso Thank You for your interest in my project!

This was actual a [documented issue with API Gateway/Lambda function URLs](https://github.com/sveltejs/kit/issues/7098).

Iv [implemented a fix](https://github.com/yarbsemaj/sveltekit-adapter-lambda/blob/6a5ffb7abaf3d9659383cb22e0a65e61bf25fad6/src/router.js#L8) in the adapter (v1.2.1) and it looks to be working correctly now.

![image](https://github.com/yarbsemaj/sveltekit-serverless-starter/assets/17494632/c654715d-ceef-4734-8bf4-1856d959c617)
